export { default as SectionButton } from './SectionButton/SectionButton'
export { default as SectionButtons } from './SectionButton/SectionButtons'
export { default as NavBar } from './Navbar/Navbar'
export { default as Accordion } from './Accordion/Accordion'
export { default as Wave } from './Wave/Wave'
export { default as Logo } from './Logo/Logo'
export { default as Footer } from './Footer/Footer'
